### ISSUE TITLE
Include() for an entity that has dependent entity is broken

### ISSUE THREAD

**Issue by LeroyK** [aspnet/EntityFrameworkCore#17177]
Including dependent properties via navigation properties is broken and throws various types of exceptions.

This was working fine in EF Core 2.2.

Two different exceptions are demonstrated in the example code.

**Exception 1:**
```
Exception message: 'Properties' is not a member of type 'EFCoreBugExample2.Group' (Parameter 'propertyOrFieldName')

Stack trace:
   at System.Linq.Expressions.Expression.PropertyOrField(Expression expression, String propertyOrFieldName)
   at Microsoft.EntityFrameworkCore.Internal.ExpressionExtensions.BuildPropertyAccess(Expression root, List`1 path, List`1 navigations)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationPropertyUnbindingVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationExpansionReducingVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryOptimizer.Visit(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at EFCoreBugExample2.Program.<Main>d__1.MoveNext() in C:\TestProjects\EFCoreBugExample2\EFCoreBugExample2\Program.cs:line 61
```

**Exception 2:**
```
Exception message: No coercion operator is defined between types 'EFCoreBugExample2.UserProperties' and 'EFCoreBugExample2.GroupProperties'.

Stack trace:
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.IncludeExpression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.NavigationExpansion.Internal.NavigationExpansionReducingVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryOptimizer.Visit(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at EFCoreBugExample2.Program.<Main>d__1.MoveNext() in C:\TestProjects\EFCoreBugExample2\EFCoreBugExample2\Program.cs:line 55
```

### Steps to reproduce
Use the following code to reproduce:

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading.Tasks;

namespace EFCoreBugExample2
{
    class Program
    {
        public static string ConnectionString = "Server=.\\SQLEXPRESS;Database=ExampleDb3;MultipleActiveResultSets=true;Integrated Security=true";

        static async Task Main(string[] args)
        {
            var options = new DbContextOptionsBuilder()
                .UseApplicationServiceProvider(
                    new ServiceCollection()
                    .AddLogging(loggingBuilder => loggingBuilder.AddConsole())
                    .BuildServiceProvider())
                .UseSqlServer(ConnectionString)
                .Options;

            using (var db = new ExampleContext(options))
            {
                db.ChangeTracker.Entries();

                db.Users.Add(new User
                {
                    Properties = new UserProperties
                    {
                        Name = "John Doe",
                        BirthDate = DateTime.UtcNow
                    },
                    Group = new Group
                    {
                        Details = new GroupDetails
                        {
                            Properties = new GroupProperties
                            {
                                Name = "Lost & found"
                            }
                        }
                    }
                });

                await db.SaveChangesAsync();
            }

            using (var db = new ExampleContext(options))
            {
                // Works
                var firstGroupDetails = await db
                    .GroupDetails
                    .FirstOrDefaultAsync();

                // Fails (Exception 1)
                var firstGroup = await db
                    .Groups
                    .Include(x => x.Details)
                    .FirstOrDefaultAsync();

                // Fails (Exception 2)
                var firstUser = await db
                    .Users
                    .Include(x => x.Group.Details)
                    .FirstOrDefaultAsync();
            }
        }
    }

    public class ExampleContext : DbContext
    {
        public DbSet<User> Users { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<GroupDetails> GroupDetails { get; set; }

        public ExampleContext(DbContextOptions options) : base(options) { }
        protected ExampleContext() { }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>()
                .OwnsOne(x => x.Properties);

            modelBuilder.Entity<GroupDetails>()
                .OwnsOne(x => x.Properties);

            base.OnModelCreating(modelBuilder);
        }
    }

    public class User
    {
        [Key]
        public long Id { get; set; }

        [Timestamp]
        public byte[] RowVersion { get; set; }

        [ForeignKey(nameof(Group))]
        public long GroupId { get; set; }

        public Group Group { get; set; }

        public UserProperties Properties { get; set; }
    }

    public class Group
    {
        [Key]
        public long Id { get; set; }

        [Timestamp]
        public byte[] RowVersion { get; set; }

        public GroupDetails Details { get; set; }
    }

    public class GroupDetails
    {
        [Key]
        [ForeignKey(nameof(Group))]
        public long GroupId { get; set; }

        public Group Group { get; set; }

        [Timestamp]
        public byte[] RowVersion { get; set; }

        public GroupProperties Properties { get; set; }
    }

    public class UserProperties
    {
        public string Name { get; set; }

        public DateTime BirthDate { get; set; }
    }

    public class GroupProperties
    {
        public string Name { get; set; }
    }

    public class ExampleContextDesignTimeDbContextFactory : IDesignTimeDbContextFactory<ExampleContext>
    {
        public ExampleContext CreateDbContext(string[] args) => new ExampleContext(
            new DbContextOptionsBuilder<ExampleContext>()
            .UseSqlServer(Program.ConnectionString)
            .Options);
    }
}

```

### Further technical details
EF Core version: 3.0.0-preview8.19405.11
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1903
IDE: Visual Studio 16.3.0 Preview 2.0

**Comment by smitpatel** [comment]
Works in Entity Framework Core 3.0.0-preview9.19415.1 (daily build)
Fixed in new nav expansion.
